# Generated by Django 4.1.4 on 2022-12-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0002_choice_question_delete_posts_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
